# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build Release"
  lane :build_aab do |options|
    should_publish = options.fetch(:should_publish, false)

    gradle(
      task: "clean bundleRelease",
      print_command: false,
    )

    if should_publish
      supply_params = {
        track: "alpha",
        # defaults to completed
        release_status: "draft",
      }
      supply(supply_params)
    end
  end
end
