# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

AAB_PATH ="./app/build/outputs/budnle/release/app-release.aab"

default_platform(:android)

platform :android do
  desc "Build Release"
  lane :build_aab do |options|
    should_publish = options.fetch(:should_publish, false)

    gradle(
      task: "clean bundleRelease",
      print_command: false,
    )

    if should_publish
      supply_params = {
        package_name: "com.smartmetmobile"
        track: "alpha",
        # defaults to completed
        release_status: "draft",
        aab: AAB_PATH,
        skip_upload_metadata: true,
        skip_upload_images: true,
        # changle logs could be included later
        skip_upload_changelogs: true,
        skip_upload_screenshots: true,
        SUPPLY_JSON_KEY_DATA: ENV["SUPPLY_JSON_KEY_DATA"]
      }
      supply(supply_params)
    end
  end
end
