on:
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to Google Play"
        required: true
        default: "false"
      locale:
        description: "Language code (available: [FI, KG])"
        required: true
        default: "FI"

name: Build Android
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.19.0]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install Dependencies
        run: yarn install

      - name: Install Ruby Dependencies
        run: gem install bundler && bundle install
        working-directory: android

      - name: Decode Environment Variables
        if: ${{ github.event.inputs.locale == 'FI'}}
        run: |
          echo $DOT_ENV | base64 --decode > .env
        env:
          DOT_ENV: ${{ secrets.DOT_ENV_FI }}

      - name: Decode Environment Variables
        if: ${{ github.event.inputs.locale == 'KG'}}
        run: |
          echo $DOT_ENV | base64 --decode > .env
        env:
          DOT_ENV: ${{ secrets.DOT_ENV_KG }}

      - name: Validate Google Supple Json Key
        env:
          SUPPLY_JSON_KEY_DATA: ${{ secrets.GOOGLE_SUPPLY_JSON_KEY }}
        run: bundle exec fastlane validate
        working-directory: android

      - name: Fastlane Build AAB
        env:
          ANDROID_RELEASE_STORE_FILE: ${{ secrets.ANDROID_RELEASE_STORE_FILE }}
          ANDROID_RELEASE_STORE_PASSWORD: ${{ secrets.ANDROID_RELEASE_STORE_PASSWORD }}
          ANDROID_RELEASE_KEY_ALIAS: ${{ secrets.ANDROID_RELEASE_KEY_ALIAS }}
          ANDROID_RELEASE_KEY_PASSWORD: ${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}
          SUPPLY_JSON_KEY_DATA: ${{ secrets.GOOGLE_SUPPLY_JSON_KEY }}
        run: bundle exec fastlane build_aab should_publish:${{ github.event.inputs.publish }}
        working-directory: android

      - name: Upload AAB
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/
